[[simpson]]
arch = "aarch64"
git-tree-sha1 = "479d2f52a24a8b62929c0e79ee2780751a99493a"
os = "macos"

    [[simpson.download]]
    sha256 = "054fbb013fb2f1e0e7a0c1bdc05e234393464f27baa3cd8e2556add8648cae6d"
    url = "https://github.com/youwuyou/simpson_jll.jl/releases/download/simpson-v0.0.1+0/simpson.v0.0.1.aarch64-apple-darwin.tar.gz"
[[simpson]]
arch = "aarch64"
git-tree-sha1 = "0c04c607895ccae0320ea6c4d498a415498dffdd"
libc = "glibc"
os = "linux"

    [[simpson.download]]
    sha256 = "57cc0dea6b056b94c0106fb8b41d3b6db61f936d775e27f4c8a34a862adc87a7"
    url = "https://github.com/youwuyou/simpson_jll.jl/releases/download/simpson-v0.0.1+0/simpson.v0.0.1.aarch64-linux-gnu.tar.gz"
[[simpson]]
arch = "aarch64"
git-tree-sha1 = "30e9e1377de88f619bc4ca1bf52d10827b166d70"
libc = "musl"
os = "linux"

    [[simpson.download]]
    sha256 = "1155aacb0eed6b81c72882c8391976f71c56b0d731cc62e2e3dd45149da3aed7"
    url = "https://github.com/youwuyou/simpson_jll.jl/releases/download/simpson-v0.0.1+0/simpson.v0.0.1.aarch64-linux-musl.tar.gz"
[[simpson]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "324472f8f3f8b842831c4fbf3b15b23d77c039ed"
libc = "glibc"
os = "linux"

    [[simpson.download]]
    sha256 = "2bcd8d244271df4d42516fb8eabbfd7323cb43e772d618fa4a66052aaefbb300"
    url = "https://github.com/youwuyou/simpson_jll.jl/releases/download/simpson-v0.0.1+0/simpson.v0.0.1.armv6l-linux-gnueabihf.tar.gz"
[[simpson]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2fe2d954a038a4195d6625a5a83acfd1c4351e1e"
libc = "musl"
os = "linux"

    [[simpson.download]]
    sha256 = "ed0a8f7383ef51a30b9a5d48c9eb206c0b1753da250d01926ffbf4005d41b91c"
    url = "https://github.com/youwuyou/simpson_jll.jl/releases/download/simpson-v0.0.1+0/simpson.v0.0.1.armv6l-linux-musleabihf.tar.gz"
[[simpson]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7428417fb7ee9868d4cf1ee3951d7507abb17380"
libc = "glibc"
os = "linux"

    [[simpson.download]]
    sha256 = "6ccd8a59be8e505f811c152c6f0787b934b63b3a1094dc7789eca9acd954af1f"
    url = "https://github.com/youwuyou/simpson_jll.jl/releases/download/simpson-v0.0.1+0/simpson.v0.0.1.armv7l-linux-gnueabihf.tar.gz"
[[simpson]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "169c32091163bf6ded2ae8327cdc98c109503729"
libc = "musl"
os = "linux"

    [[simpson.download]]
    sha256 = "27f512751db09eff9a5636f3e5c6e4e02b90741327ac97a93bfe41f86d3fdb32"
    url = "https://github.com/youwuyou/simpson_jll.jl/releases/download/simpson-v0.0.1+0/simpson.v0.0.1.armv7l-linux-musleabihf.tar.gz"
[[simpson]]
arch = "i686"
git-tree-sha1 = "23d9feb9be6f8a1ea3512b7f84e3f02dbe789c85"
libc = "glibc"
os = "linux"

    [[simpson.download]]
    sha256 = "7cd2832d51a298bc53c1df34c41b83c511e9e1d13ca62d6f05095611d56e50b6"
    url = "https://github.com/youwuyou/simpson_jll.jl/releases/download/simpson-v0.0.1+0/simpson.v0.0.1.i686-linux-gnu.tar.gz"
[[simpson]]
arch = "i686"
git-tree-sha1 = "4d72c5822d1f0a1e1bdbda1386959ae6c16bd8f0"
libc = "musl"
os = "linux"

    [[simpson.download]]
    sha256 = "ee4252bc7fccd7035df91d5439960cd79b34a902c17a802ad1bf69d09f0e16b7"
    url = "https://github.com/youwuyou/simpson_jll.jl/releases/download/simpson-v0.0.1+0/simpson.v0.0.1.i686-linux-musl.tar.gz"
[[simpson]]
arch = "powerpc64le"
git-tree-sha1 = "09cb3ff9f64cf2ab6800c5dd5bcbba720569e0ee"
libc = "glibc"
os = "linux"

    [[simpson.download]]
    sha256 = "b79830687f3ca3980e5aae334f4b0873529a7a88d867abc90b3a00518ea97d91"
    url = "https://github.com/youwuyou/simpson_jll.jl/releases/download/simpson-v0.0.1+0/simpson.v0.0.1.powerpc64le-linux-gnu.tar.gz"
[[simpson]]
arch = "x86_64"
git-tree-sha1 = "d91cc9df25a5d86ae0b0b97504c12d285df1b63f"
os = "macos"

    [[simpson.download]]
    sha256 = "bd273d6b4a8951320255fd2884eab515571444dea80532e59ded8606d91ac72c"
    url = "https://github.com/youwuyou/simpson_jll.jl/releases/download/simpson-v0.0.1+0/simpson.v0.0.1.x86_64-apple-darwin.tar.gz"
[[simpson]]
arch = "x86_64"
git-tree-sha1 = "989430912394f19fb4ec96a345d5a6ef346eae22"
libc = "glibc"
os = "linux"

    [[simpson.download]]
    sha256 = "6945f12746909a754b58770db849c65eebaeb19d268596ab39c12c3589fa77a9"
    url = "https://github.com/youwuyou/simpson_jll.jl/releases/download/simpson-v0.0.1+0/simpson.v0.0.1.x86_64-linux-gnu.tar.gz"
[[simpson]]
arch = "x86_64"
git-tree-sha1 = "77d1cbc0e8ede3b42afbf431400e6394c1d8d773"
libc = "musl"
os = "linux"

    [[simpson.download]]
    sha256 = "954117c292cc81710372f80ac06f32b711faddb95445313f58957b85ad29c40c"
    url = "https://github.com/youwuyou/simpson_jll.jl/releases/download/simpson-v0.0.1+0/simpson.v0.0.1.x86_64-linux-musl.tar.gz"
[[simpson]]
arch = "x86_64"
git-tree-sha1 = "95948dc6b5dd4dd84208ffa129b1eb61f2ceb3c9"
os = "freebsd"

    [[simpson.download]]
    sha256 = "88be96de27cec52fea8aa722ac2b7c55c5c8908067dcc479b3020780b5f1e55f"
    url = "https://github.com/youwuyou/simpson_jll.jl/releases/download/simpson-v0.0.1+0/simpson.v0.0.1.x86_64-unknown-freebsd.tar.gz"
