# Autogenerated wrapper script for simpson_jll for x86_64-apple-darwin
export libsimpson

JLLWrappers.@generate_wrapper_header("simpson")
JLLWrappers.@declare_library_product(libsimpson, "@rpath/libsimpson.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libsimpson,
        "lib/libsimpson.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
